name: CI

on:
  push:
    branches: [ main, feat/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  unit:
    name: CI / Unit tests (not integration)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # pytest is installed here so we don't pollute requirements.txt
          pip install pytest

      - name: Run unit tests
        env:
          PYTHONPATH: src
        run: |
          pytest -q -m "not integration" --disable-warnings --maxfail=1

  integration:
    name: CI / Integration tests (main/manual)
    # This job still runs on push/PR, but it becomes green when there are no integration tests.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Optional: pass any reporter secrets if your integration tests need them
      - name: Run integration tests (graceful when none exist)
        env:
          PYTHONPATH: src
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REPORTER_MODEL: ${{ secrets.REPORTER_MODEL }}
          REPORTER_TEMPERATURE: ${{ secrets.REPORTER_TEMPERATURE }}
        shell: bash
        run: |
          set -e
          pytest -q -m "integration" --disable-warnings --maxfail=1 || rc=$?
          # pytest exit codes: 0=ok, 1=fails, 5=no tests collected
          if [[ "${rc:-0}" -eq 5 ]]; then
            echo "No integration tests collected. Marking job as success."
            exit 0
          else
            exit "${rc:-0}"
          fi
