name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    env:
      # Prevent accidental network calls to OpenAI during tests
      OPENAI_API_KEY: "test-only-no-network"
      # Cache location for HF models (sentiment agent); keeps runs fast after first cache
      TRANSFORMERS_CACHE: ${{ runner.temp }}/hf_cache
      # Ensure imports work like locally
      PYTHONPATH: src
      # Optional: if your code supports a small sentiment model via env
      # SENTIMENT_MODEL: sshleifer/tiny-distilroberta-base

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Cache Hugging Face models
        uses: actions/cache@v4
        with:
          path: ${{ env.TRANSFORMERS_CACHE }}
          key: hf-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            hf-${{ runner.os }}-

      - name: Install system deps (parquet/zstd support)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libzstd1

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # helpful for nicer pytest output
          pip install pytest

      - name: Run tests
        run: |
          pytest -q
